### ISSUE TITLE
not spooky

### ISSUE THREAD

**Issue by flashwave** [Pepperrika/SpookyRepository#1]
i want a refund

**Comment by Pepperrika** [comment]
###, ,##, ,##,
        #  # #  # #  #
        ###  #  # #  #
        #  # #  # #  #
        ###' '##' '##'
             .--,
            /  (
           /    \
          /      \ 
         /  0  0  \
 ((()   |    ()    |   ()))
 \  ()  (  .____.  )  ()  /
  |` \_/ \  `""`  / \_/ `|
  |       `.'--'.`       |
   \        `""`        /
    \                  /
     `.              .'    ,
      |`             |  _.'|
      |              `-'  /
      \                 .'
       `.____________.-'
now its spooky
